
type: develop

FASTAPI:
  HOST : localhost
  PORT : 8000
  API_PREFIX : /fastapi
  WORKERS : 1
  RELOAD : True
  LOG_LEVEL : info

HTTP:
  BATCH_THRESHOLD : 256
  BATCH_TIMEOUT : 1.0 # 1sec

AI:
  FREE_MEM_THRESHOLD : 2 # GB
  INFERENCE_MODE : vlm
  MODEL_NAME : BLIP
  MODEL_ID: Salesforce/blip-image-captioning-base
  TASK_TYPE : VQA
  MAX_NEW_TOKENS : 32
  DEVICE_MAP : auto
  DTYPE : float16
  VLM_QUESTION : What objects can you see?
  VLM_PROMPOT : "Question: What objects are in this image? Answer:"
  NORM_MEAN :
  NROM_STD : 
  
