// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: SomniAI.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImage) Reset() {
	*x = SendImage{}
	mi := &file_SomniAI_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImage) ProtoMessage() {}

func (x *SendImage) ProtoReflect() protoreflect.Message {
	mi := &file_SomniAI_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImage.ProtoReflect.Descriptor instead.
func (*SendImage) Descriptor() ([]byte, []int) {
	return file_SomniAI_proto_rawDescGZIP(), []int{0}
}

func (x *SendImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendImage) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_SomniAI_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_SomniAI_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_SomniAI_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_SomniAI_proto protoreflect.FileDescriptor

const file_SomniAI_proto_rawDesc = "" +
	"\n" +
	"\rSomniAI.proto\x12\n" +
	"somniai.v1\"5\n" +
	"\tSendImage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2@\n" +
	"\x06PushGo\x126\n" +
	"\n" +
	"StreamToGo\x12\x15.somniai.v1.SendImage\x1a\x0f.somniai.v1.Ack(\x012@\n" +
	"\x06PushPy\x126\n" +
	"\n" +
	"StreamToPy\x12\x15.somniai.v1.SendImage\x1a\x0f.somniai.v1.Ack(\x01B\x1eZ\x1csomniai.com/grpc/proto;protob\x06proto3"

var (
	file_SomniAI_proto_rawDescOnce sync.Once
	file_SomniAI_proto_rawDescData []byte
)

func file_SomniAI_proto_rawDescGZIP() []byte {
	file_SomniAI_proto_rawDescOnce.Do(func() {
		file_SomniAI_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SomniAI_proto_rawDesc), len(file_SomniAI_proto_rawDesc)))
	})
	return file_SomniAI_proto_rawDescData
}

var file_SomniAI_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SomniAI_proto_goTypes = []any{
	(*SendImage)(nil), // 0: somniai.v1.SendImage
	(*Ack)(nil),       // 1: somniai.v1.Ack
}
var file_SomniAI_proto_depIdxs = []int32{
	0, // 0: somniai.v1.PushGo.StreamToGo:input_type -> somniai.v1.SendImage
	0, // 1: somniai.v1.PushPy.StreamToPy:input_type -> somniai.v1.SendImage
	1, // 2: somniai.v1.PushGo.StreamToGo:output_type -> somniai.v1.Ack
	1, // 3: somniai.v1.PushPy.StreamToPy:output_type -> somniai.v1.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SomniAI_proto_init() }
func file_SomniAI_proto_init() {
	if File_SomniAI_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SomniAI_proto_rawDesc), len(file_SomniAI_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_SomniAI_proto_goTypes,
		DependencyIndexes: file_SomniAI_proto_depIdxs,
		MessageInfos:      file_SomniAI_proto_msgTypes,
	}.Build()
	File_SomniAI_proto = out.File
	file_SomniAI_proto_goTypes = nil
	file_SomniAI_proto_depIdxs = nil
}
